version: '3'
services:
  diary:
    build: https://github.com/dodaucy/diary.git
    environment:
      DATABASE: "mysql://diary:diary@mariadb/diary"
      PASSWORD_HASH: ${PASSWORD_HASH:?Password hash not set}
    env_file:
      - .env
    ports:
      - 127.0.0.1:${PORT:?Port not set}:8000
    depends_on:
      - mariadb
    restart: always
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: diary
      MYSQL_USER: diary
      MYSQL_PASSWORD: diary
    volumes:
      - ./data/mariadb:/var/lib/mysql
    restart: always
